### ISSUE TITLE
Keyword IN not supported

### ISSUE THREAD

**Issue by pedja4** [kohsuke/groovy-sandbox#24]
`KEYWORD_IN` is not supported, trying to execute this simple script

    def status = "status 1";
    def b = status in ["status 1", "status 2", "status 3", "status 4"];

throws exception

    java.lang.IllegalArgumentException: 573
	at org.kohsuke.groovy.sandbox.impl.Ops.binaryOperatorMethods(Ops.java:29) ~[Ops.class:?]

where `573` is the value of `org.codehaus.groovy.syntax.Types.KEYWORD_IN`

**Comment by kohsuke** [comment]
Fixed by pull request #26
